
// testing requests, make sure to install Rest Client form VScode extensions.

GET http://localhost:3001/patients

###


POST http://localhost:3001/patients
Content-Type: application/json

{
    "name": "Omar Diab",
    "age": 32,
    "email": "omar@example.com",
    "phoneNumber": "891-341-7163",
    "address": "24 Harvard St.",
    "city": "Cambridge",
    "state": "MA",
    "zipCode": "32761"
}


###

PATCH http://localhost:3001/patients/61f81f239180161ec9270e13
Content-Type: application/json

{
    "age": "33"
}


###

GET http://localhost:3001/patients/61f81f239180161ec9270e13
