
// testing requests, make sure to install Rest Client form VScode extensions.

GET http://localhost:3001/patients

###


POST http://localhost:3001/patients
Content-Type: application/json

{
    "name": "Omar Diab",
    "age": 32,
    "email": "omar@example.com",
    "phoneNumber": "891-341-7163",
    "address": "24 Harvard St.",
    "city": "Cambridge",
    "state": "MA",
    "zipCode": "32761"
}

###

DELETE http://localhost:3001/patients/61fadeb421d63c8ab45dadb7


###

PATCH http://localhost:3001/patients/61f81f239180161ec9270e13
Content-Type: application/json

{
    "age": "33"
}


###

GET http://localhost:3001/patients/61f81f239180161ec9270e13


###
###
###

// testing requests for exams

GET http://localhost:3001/exams


###

POST http://localhost:3001/exams
Content-Type: application/json

{
    "numHours": 5,
    "xRayImageLink": "https://media.istockphoto.com/photos/human-thoracic-cavity-xray-film-picture-id1212285302?s=612x612",
    "keyFindings": "Treaky opacities in bilateral mid and left lower lung. Patchy opacities in the right lower lung. No pleural effusion.",
    "brixiaScores": [2, 1, 3, 1, 2, 1],
    "patientID": "61f72fa6171f31f7b5bc80ad"
}