
// testing requests, make sure to install Rest Client from VScode extensions.

GET http://localhost:3001/patients

###


POST http://localhost:3001/patients
Content-Type: application/json

{
    "name": "Amanda Zhang",
    "age": 20,
    "email": "amanda@example.com",
    "phoneNumber": "891-462-7810",
    "address": "29 Main St.",
    "city": "Boston",
    "state": "MA",
    "zipCode": "31478",
    "sex": "F"
}

###

DELETE http://localhost:3001/patients/620ac34662cf3a2d42355a79


###

PATCH http://localhost:3001/patients/6209a0f0efb1b5f366f63993
Content-Type: application/json

{
    "name": "James Zhang",
    "sex": "M"
}


###

GET http://localhost:3001/patients/620ac6479086d5aef30fddc5


###
###
###

// testing requests for exams

GET http://localhost:3001/exams


###

POST http://localhost:3001/exams
Content-Type: application/json

{
    "numHours": 2,
    "xRayImageLink": "https://media.istockphoto.com/photos/radiographic-image-or-xray-image-of-human-chest-for-a-medical-check-picture-id1133123956?k=20&m=1133123956&s=612x612&w=0&h=KgPzECbwi3vhb5VtFv7WMtCqdW4Fb4j2yiprHATLXyo=",
    "keyFindings": "Lung volumes remain low but there appears to have been clearing since prior radiograph.",
    "brixiaScores": "133211",
    "patientID": "61f81f239180161ec9270e13"
}


###

GET http://localhost:3001/exams/61f98fd80d94af134b0639af

###

DELETE http://localhost:3001/exams/6212e5c8e9315f89380c5993